// Generates the API types from the backend's OpenAPI document.
//
//   npm run api:types                          # from the backend's main branch (DEFAULT_SPEC_URL)
//   npm run api:types -- ../HRWebApp/docs/openapi.json   # from a local file (or any URL)
//   OPENAPI_SPEC=http://localhost:8080/v3/api-docs npm run api:types
//   npm run api:types -- --pinned              # offline: regenerate from the committed copy
//   npm run api:types -- --check               # CI: fail if the backend's spec no longer matches
//
// Writes two files, both committed so builds never need the network:
//   src/api/generated/openapi.json   the spec that was used (pinned copy, `servers` removed)
//   src/api/generated/schema.d.ts    the types generated from it by openapi-typescript
import openapiTS, { astToString } from 'openapi-typescript';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const DEFAULT_SPEC_URL = 'https://raw.githubusercontent.com/jacidProgrammer/HRWebApp/main/docs/openapi.json';
const OUT_DIR = resolve(import.meta.dirname, '../src/api/generated');
const SPEC_FILE = resolve(OUT_DIR, 'openapi.json');
const TYPES_FILE = resolve(OUT_DIR, 'schema.d.ts');

const HEADER = `/**
 * Generated by \`npm run api:types\` (openapi-typescript) from ./openapi.json, the backend's OpenAPI
 * document. Do not edit by hand: src/api/types.ts derives the app's types from it.
 */

`;

const args = process.argv.slice(2);
const check = args.includes('--check');
const pinned = args.includes('--pinned');
const source = args.find((arg) => !arg.startsWith('--')) ?? process.env.OPENAPI_SPEC ?? (pinned ? SPEC_FILE : DEFAULT_SPEC_URL);
const isUrl = /^https?:\/\//.test(source);

class SpecNotPublished extends Error {}

async function loadSpec() {
  if (!isUrl) return JSON.parse(await readFile(resolve(source), 'utf8'));
  const response = await fetch(source, { headers: { Accept: 'application/json' } });
  if (response.status === 404) throw new SpecNotPublished(`${source} answered 404`);
  if (!response.ok) throw new Error(`GET ${source} failed: ${response.status} ${response.statusText}`);
  return response.json();
}

/** `servers` holds the host and port of whoever exported the document: not part of the contract. */
function normalise(spec) {
  const copy = { ...spec };
  delete copy.servers;
  return copy;
}

async function generate(spec) {
  return HEADER + astToString(await openapiTS(spec));
}

let spec;
try {
  spec = normalise(await loadSpec());
} catch (error) {
  if (check && error instanceof SpecNotPublished) {
    // No document on the backend's main branch (not published, or moved): nothing to compare with.
    console.log(`::warning title=API contract check skipped::${error.message}. The backend's OpenAPI document was not found, so the committed types were not checked.`);
    process.exit(0);
  }
  console.error(`Could not load the OpenAPI document from ${source}: ${error.message}`);
  process.exit(1);
}

const types = await generate(spec);

if (check) {
  const committed = await readFile(TYPES_FILE, 'utf8').catch(() => '');
  if (committed === types) {
    console.log(`API contract OK: src/api/generated/schema.d.ts matches ${source}`);
    process.exit(0);
  }
  console.log(
    `::error title=API contract drift::src/api/generated/schema.d.ts no longer matches the backend's OpenAPI document (${source}). ` +
      'Run `npm run api:types`, fix any type errors in src/api/types.ts, and commit both files in src/api/generated/.',
  );
  // Show what changed, so the log alone explains the failure.
  const before = committed.split('\n');
  const after = types.split('\n');
  const removed = before.filter((line) => !after.includes(line));
  const added = after.filter((line) => !before.includes(line));
  for (const line of removed.slice(0, 40)) console.log(`- ${line}`);
  for (const line of added.slice(0, 40)) console.log(`+ ${line}`);
  process.exit(1);
}

await mkdir(OUT_DIR, { recursive: true });
if (!pinned) await writeFile(SPEC_FILE, `${JSON.stringify(spec, null, 2)}\n`);
await writeFile(TYPES_FILE, types);
console.log(`Generated src/api/generated/schema.d.ts from ${pinned ? 'the pinned copy' : source}`);
